### ISSUE TITLE
TypeError's on Node 14.8.2 with potential solution

### ISSUE THREAD

**Issue by twoxfh** [gyf304/sqlite-wasm#1]
@gyf304 I was getting TypeError's in the Mocha tests with Node 14.8.2 with tests involving BigInt. 

In the package.json for tests I added "--experimental-wasm-bigint" and all tests compiled successfully. If you accept pull requests I can drum one up. Curious on your vision for this project.

**Comment by gyf304** [comment]
Hi @twoxfh , thank you for your support in this library. If I'm understanding this correctly, the addition of this flag will not impact the users of this library and only impacts development on this library. This library targets node 16 / current browsers and is intended to be developed using node 16. The `--experimental-wasm-bigint` flag is not needed for node 16. Would it be possible for you to use node 16 given that 14 is out of active support and going to be EOL in 8 months? You can still use this library in node 14 by adding `--experimental-wasm-bigint` in the application.

With regards to the vision of this project: This library is developed to support https://github.com/gyf304/sqlnb , an online, front-end only sql notebook / playground, which is my current toy project.
The broader goal of this library is to have a sane, minimal and well-tested wrapper around vanilla (or, as vanilla as possible) SQLite, while providing an escape hatch for more advanced usages by directly exposing raw SQLite APIs.

**Comment by twoxfh** [comment]
Appreciate the feedback @gyf304, I did not see the node 16 dependency, will upgrade. Will check out the notebook too. Thanks.
